export const countries = [
  {
    id: 40,
    alpha2: "at",
    alpha3: "aut",
    name: "Austria",
    names: [
      "Autriche",
      "Österreich",
      "Austria",
      "Austria",
      "Áustria",
      "Oostenrijk",
      "Austria",
      "Avusturya",
      "Austria",
    ],
  },
  {
    id: 56,
    alpha2: "be",
    alpha3: "bel",
    name: "Belgium",
    names: [
      "Belgique",
      "Belgien",
      "Bélgica",
      "Belgio",
      "Bélgica",
      "België",
      "Belgia",
      "Belçika",
      "Belgium",
    ],
  },
  {
    id: 100,
    alpha2: "bg",
    alpha3: "bgr",
    name: "Bulgaria",
    names: [
      "Bulgarie",
      "Bulgarien",
      "Bulgaria",
      "Bulgaria",
      "Bulgária",
      "Bulgarije",
      "Bułgaria",
      "Bulgaristan",
      "Bulgaria",
    ],
  },
  {
    id: 191,
    alpha2: "hr",
    alpha3: "hrv",
    name: "Croatia",
    names: [
      "Croatie",
      "Kroatien",
      "Croacia",
      "Croazia",
      "Croácia",
      "Kroatië",
      "Chorwacja",
      "Hırvatistan",
      "Croatia",
    ],
  },
  {
    id: 203,
    alpha2: "cz",
    alpha3: "cze",
    name: "Czechia",
    names: [
      "Tchéquie",
      "Tschechien",
      "República Checa",
      "Rep. Ceca",
      "Chéquia",
      "Tsjechië",
      "Czechy",
      "Çekya",
      "Czechia",
    ],
  },
  {
    id: 208,
    alpha2: "dk",
    alpha3: "dnk",
    name: "Denmark",
    names: [
      "Danemark",
      "Dänemark",
      "Dinamarca",
      "Danimarca",
      "Dinamarca",
      "Denemarken",
      "Dania",
      "Danimarka",
      "Denmark",
    ],
  },
  {
    id: 233,
    alpha2: "ee",
    alpha3: "est",
    name: "Estonia",
    names: [
      "Estonie",
      "Estland",
      "Estonia",
      "Estonia",
      "Estónia",
      "Estland",
      "Estonia",
      "Estonya",
      "Estonia",
    ],
  },
  {
    id: 246,
    alpha2: "fi",
    alpha3: "fin",
    name: "Finland",
    names: [
      "Finlande",
      "Finnland",
      "Finlandia",
      "Finlandia",
      "Finlândia",
      "Finland",
      "Finlandia",
      "Finlandiya",
      "Finland",
    ],
  },
  {
    id: 250,
    alpha2: "fr",
    alpha3: "fra",
    name: "France",
    names: [
      "France",
      "Frankreich",
      "Francia",
      "Francia",
      "França",
      "Frankrijk",
      "Francja",
      "Fransa",
      "France",
    ],
  },
  {
    id: 276,
    alpha2: "de",
    alpha3: "deu",
    name: "Germany",
    names: [
      "Allemagne",
      "Deutschland",
      "Alemania",
      "Germania",
      "Alemanha",
      "Duitsland",
      "Niemcy",
      "Almanya",
      "Germany",
    ],
  },
  {
    id: 300,
    alpha2: "gr",
    alpha3: "grc",
    name: "Greece",
    names: [
      "Grèce",
      "Griechenland",
      "Grecia",
      "Grecia",
      "Grécia",
      "Griekenland",
      "Grecja",
      "Yunanistan",
      "Greece",
    ],
  },
  {
    id: 348,
    alpha2: "hu",
    alpha3: "hun",
    name: "Hungary",
    names: [
      "Hongrie",
      "Ungarn",
      "Hungría",
      "Ungheria",
      "Hungria",
      "Hongarije",
      "Węgry",
      "Macaristan",
      "Hungary",
    ],
  },
  {
    id: 372,
    alpha2: "ie",
    alpha3: "irl",
    name: "Ireland",
    names: [
      "Irlande",
      "Irland",
      "Irlanda",
      "Irlanda",
      "Irlanda",
      "Ierland",
      "Irlandia",
      "İrlanda",
      "Ireland",
    ],
  },
  {
    id: 380,
    alpha2: "it",
    alpha3: "ita",
    name: "Italy",
    names: [
      "Italie",
      "Italien",
      "Italia",
      "Italia",
      "Itália",
      "Italië",
      "Włochy",
      "İtalya",
      "Italy",
    ],
  },
  {
    id: 428,
    alpha2: "lv",
    alpha3: "lva",
    name: "Latvia",
    names: [
      "Lettonie",
      "Lettland",
      "Letonia",
      "Lettonia",
      "Letônia",
      "Letland",
      "Łotwa",
      "Letonya",
      "Latvia",
    ],
  },
  {
    id: 440,
    alpha2: "lt",
    alpha3: "ltu",
    name: "Lithuania",
    names: [
      "Lituanie",
      "Litauen",
      "Lituania",
      "Lituania",
      "Lituânia",
      "Litouwen",
      "Litwa",
      "Litvanya",
      "Lithuania",
    ],
  },
  {
    id: 442,
    alpha2: "lu",
    alpha3: "lux",
    name: "Luxembourg",
    names: [
      "Luxembourg",
      "Luxemburg",
      "Luxemburgo",
      "Lussemburgo",
      "Luxemburgo",
      "Luxemburg",
      "Luksemburg",
      "Lüksemburg",
      "Luxembourg",
    ],
  },
  {
    id: 470,
    alpha2: "mt",
    alpha3: "mlt",
    name: "Malta",
    names: [
      "Malte",
      "Malta",
      "Malta",
      "Malta",
      "Malta",
      "Malta",
      "Malta",
      "Malta",
      "Malta",
    ],
  },
  {
    id: 528,
    alpha2: "nl",
    alpha3: "nld",
    name: "Netherlands",
    names: [
      "Pays-Bas",
      "Niederlande",
      "Países Bajos",
      "Paesi Bassi",
      "Países Baixos",
      "Nederland",
      "Holandia",
      "Hollanda",
      "Netherlands",
    ],
  },
  {
    id: 616,
    alpha2: "pl",
    alpha3: "pol",
    name: "Poland",
    names: [
      "Pologne",
      "Polen",
      "Polonia",
      "Polonia",
      "Polónia",
      "Polen",
      "Polska",
      "Polonya",
      "Poland",
    ],
  },
  {
    id: 620,
    alpha2: "pt",
    alpha3: "prt",
    name: "Portugal",
    names: [
      "Portugal",
      "Portugal",
      "Portugal",
      "Portogallo",
      "Portugal",
      "Portugal",
      "Portugalia",
      "Portekiz",
      "Portugal",
    ],
  },
  {
    id: 642,
    alpha2: "ro",
    alpha3: "rou",
    name: "Romania",
    names: [
      "Roumanie",
      "Rumänien",
      "Rumania",
      "Romania",
      "Roménia",
      "Roemenië",
      "Rumunia",
      "Romanya",
      "Romania",
    ],
  },
  {
    id: 703,
    alpha2: "sk",
    alpha3: "svk",
    name: "Slovakia",
    names: [
      "Slovaquie",
      "Slowakei",
      "Eslovaquia",
      "Slovacchia",
      "Eslováquia",
      "Slowakije",
      "Słowacja",
      "Slovakya",
      "Slovakia",
    ],
  },
  {
    id: 705,
    alpha2: "si",
    alpha3: "svn",
    name: "Slovenia",
    names: [
      "Slovénie",
      "Slowenien",
      "Eslovenia",
      "Slovenia",
      "Eslovênia",
      "Slovenië",
      "Słowenia",
      "Slovenya",
      "Slovenia",
    ],
  },
  {
    id: 724,
    alpha2: "es",
    alpha3: "esp",
    name: "Spain",
    names: [
      "Espagne",
      "Spanien",
      "España",
      "Spagna",
      "Espanha",
      "Spanje",
      "Hiszpania",
      "İspanya",
      "Spain",
    ],
  },
  {
    id: 752,
    alpha2: "se",
    alpha3: "swe",
    name: "Sweden",
    names: [
      "Suède",
      "Schweden",
      "Suecia",
      "Svezia",
      "Suécia",
      "Zweden",
      "Szwecja",
      "İsveç",
      "Sweden",
    ],
  },
  {
    id: 756,
    alpha2: "ch",
    alpha3: "che",
    name: "Switzerland",
    names: [
      "Suisse",
      "Schweiz",
      "Suiza",
      "Svizzera",
      "Suíça",
      "Zwitserland",
      "Szwajcaria",
      "İsviçre",
      "Switzerland",
    ],
  },
  {
    id: 826,
    alpha2: "gb",
    alpha3: "gbr",
    name: "United Kingdom of Great Britain and Northern Ireland",
    names: [
      "Royaume-Uni",
      "Vereinigtes Königreich",
      "Reino Unido",
      "Regno Unito",
      "Reino Unido",
      "Verenigd Koninkrijk",
      "Wielka Brytania",
      "Birleşik Krallık",
      "United Kingdom of Great Britain and Northern Ireland",
    ],
  },
];
